[common.consensus_config]
max_message_len = 1048576
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
round_timeout = 3000
status_timeout = 5000
txs_block_limit = 1000

[common.general_config]
validators_count = 4

[common.services_config]

[node]
addr = "127.0.0.1:6331"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "56f224bbb06da1ed5ba3cf69266544c99c56c80b4181f5093b36d0b64fb760d9"
service_key = "491b5c11738e690cbf535fb3c258f3ff5120d674da9a4d8e9a7227fdc9b95b20"
