[common.consensus_config]
max_message_len = 1048576
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
round_timeout = 3000
status_timeout = 5000
txs_block_limit = 1000

[common.general_config]
validators_count = 4

[common.services_config]

[node]
addr = "127.0.0.1:6332"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "afa244a699f9bb6b737a8c038799f8e7713f71ba433e18c960c0b05c0866c562"
service_key = "8c7bb6fed2cf174a66e45b5d849a18028a3a49bfd0ca5d34b67f907eb6cdb7dd"
